apiVersion: v1
kind: ConfigMap
metadata:
  name: mungeconfig
data:
  MUNGE_KEY: Z6+$6Lc``c;g{DMdsu+pyo8DymAB#l%e]3<?TQSt'P@&<3jS@[o2^-ulJ&~Hr.=


---
apiVersion: v1
kind: Service
metadata: 
  name: hpc
spec:
  selector:
    type: hpc-stuff
  clusterIP: None
---
apiVersion: v1
kind: Pod
metadata:
  name: jlab-2
  labels:
    type: hpc-stuff
spec:
  hostname: jlab2
  containers:
  - name: worker
    image: djc6w/slurm_worker
    volumeMounts:
    - name: munge-key
      mountPath: /etc/munge/munge.key.tmp
  volumes:
  - name: munge-key
    configMap:
      name: mungeconfig
  subdomain: hpc
  dnsConfig:
    searches:
      - hpc.default.svc.cluster.local
---
apiVersion: v1
kind: Pod
metadata:
  name: jlab-1
  labels:
    type: hpc-stuff
spec:
  hostname: jlab1
  containers:
  - name: control
    image: djc6w/slurm_client
    volumeMounts:
    - name: munge-key
      mountPath: /etc/munge/munge.key.tmp
  volumes:
  - name: munge-key
    configMap:
      name: mungeconfig
  subdomain: hpc
  dnsConfig:
    searches:
      - hpc.default.svc.cluster.local
